Add friends likes
Anarmard/java-filmorate pull request #2
Opened 2022-08-09 00:44 UTC by Anarmard

2022-08-10 11:42 UTC, alexache requested changes
Оставил немного комментариев по коду

2022-08-10 11:42 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/model/ErrorResponse.java
> +    String error;
Не хватает модификатора доступа Private

2022-08-10 11:42 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    void checkFilmID (Long filmId) {
Не хватает модификатора доступа Private

2022-08-10 11:42 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +    public void checkUserID (Long userId) {
Метод полностью дублирует такой же в FilmService, что уже не очень хорошо. Может добавить такой метод в сам сторадж, если очень хочется проверять сначала? 
А если смотреть на будущее,  то такая проверка пожалуй лишняя, лучше один раз вызывать метод получения объекта по айди, чем несколько раз

2022-08-10 11:42 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmStorage.java
> +    public Long getNextId();
Все методы внутри интерфейса и так считаются публичными, Указывать им public излишне

2022-08-10 11:42 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmStorage.java
> +    public Long getNextId();
Нужен ли метод получения следующего айди публичным?

2022-08-10 11:42 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/InMemoryUserStorage.java
> +        List<User> listOfCommonFriends = new ArrayList<>();
Такой алгоритм очень неоптимальный: будет лучше если список друзей будет Set, а не List, тогда можно фильтровать элементы одного списка по признаку наличия во втором списке

2022-08-10 11:42 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/UserStorage.java
> +    public Long getNextId();
Такой же комментарий про public в интерфейсе и про то, нужен ли метод получения айди в интерфейсе

2022-08-10 19:23 UTC, Anarmard commented on src/main/java/ru/yandex/practicum/filmorate/model/ErrorResponse.java
> +    String error;
OK

2022-08-10 19:24 UTC, Anarmard commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    void checkFilmID (Long filmId) {
OK

2022-08-10 19:26 UTC, Anarmard commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmStorage.java
> +    public Long getNextId();
Спасибо, поправил

2022-08-10 19:29 UTC, Anarmard commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmStorage.java
> +    public Long getNextId();
Убрал в интерфейсе public. 
Если поставить тут private, то возникает ошибка.

2022-08-10 19:31 UTC, Anarmard commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/UserStorage.java
> +    public Long getNextId();
Понял, спасибо! поменял на private в storage, в интерфейсе удалил

2022-08-10 19:32 UTC, Anarmard commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmStorage.java
> +    public Long getNextId();
Понял, спасибо! поменял на private в storage, в интерфейсе удалил

2022-08-11 04:27 UTC, Anarmard commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +    public void checkUserID (Long userId) {
Понял, удалил эту проверку из кода.

2022-08-11 22:29 UTC, Anarmard commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/InMemoryUserStorage.java
> +        List<User> listOfCommonFriends = new ArrayList<>();
Спасибо, переделал

2022-08-12 13:09 UTC, alexache approved these changes
Остался только один follow-up комментарий-пожелание использовать Stream API во всю

2022-08-12 13:09 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/InMemoryUserStorage.java
> +        Set<Long> setIdOfCommonFriends = user.getFriendsID().stream()
Не обратил внимание, что возвращается объект User, опять же можно воспользоваться Stream API и дописать в эту строчку перед .collect() еще одну цепь - .map(User::getUserByID), а то использование цикла уже не вписывается после использования стримов

2022-08-14 10:24 UTC, Anarmard commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/InMemoryUserStorage.java
> +        Set<Long> setIdOfCommonFriends = user.getFriendsID().stream()
.map(this::getUserByID) - ИДЕА приняло в таком виде. Спасибо, Александр, за совет! 
Понимаю надо практиковаться со стримами, но пока к сожалению не успеваю выполнять даже основную программу.

2022-08-14 10:35 UTC, merged