Add database
Anarmard/java-filmorate pull request #3
Opened 2022-09-02 02:11 UTC by Anarmard

Не могу понять/увидеть, почему не создается фильм. Create Film. 

По User все тесты проходят.

2022-09-02 21:10 UTC, alexache requested changes
Не ручаюсь, что нашел все проблемы, но комментарии должны помочь исправить прохождение билда и создание фильмов, пришлось локально подебажить

2022-09-02 21:10 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/model/Mpa.java
> +    private Long ratingMpaId;
Поля должны называться id и name иначе тысты постман не пройдут

2022-09-02 21:10 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/model/Genre.java
> +    private Long genreId;
Ёти поля тоже должны называться id и name дляп прохождения тестов

2022-09-02 21:10 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +    public Optional<Film> createFilm(Film film) {
Не ояень логияно возвращать опшенл на создание сущности. Если не полцчится создать должна быть ошибка, а не просто пустоц опшенл

2022-09-02 21:10 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/UserDbStorage.java
> +        return getUserByID(simpleJdbcInsert.executeAndReturnKey(toMapUser(user)).longValue());
Тоже довольно странная конструкция с добавление и сразу поиском по БД

2022-09-02 21:10 UTC, alexache commented on src/main/resources/application.properties
> +spring.datasource.url=jdbc:h2:mem:filmorate
почему только в памяти а не в файле?

2022-09-02 21:10 UTC, alexache commented on src/test/java/ru/yandex/practicum/filmorate/FilmorateApplicationTests.java
> +		Optional<User> userOptional = userStorage.getUserByID(1L);
а откуда ожидается пользователь с таким айди на старте пустоц системы? Из-за этого падающего теста ломается сборка и соотвественно не видно остальных постман тестов

2022-09-04 16:11 UTC, Anarmard commented on src/main/java/ru/yandex/practicum/filmorate/model/Mpa.java
> +    private Long ratingMpaId;
Поправил. Спасибо! А как ты узнаешь, как должны называться поля для успешного прохождения тестов в постмане?Это надо смотреть в постмане или в идеи? Если в постмане, то это на вкладке Tests?(pm.expect(jsonData.**id**).to.eql(1))

2022-09-04 16:15 UTC, Anarmard commented on src/main/java/ru/yandex/practicum/filmorate/model/Genre.java
> +    private Long genreId;
Сделал

2022-09-04 16:21 UTC, Anarmard commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        if (filmResponse.isEmpty()) {
Спасибо, поправил!

2022-09-04 21:52 UTC, Anarmard commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public Optional<Film> getFilmByID(@PathVariable Long id) {
Поправил, спасибо.

2022-09-04 22:38 UTC, Anarmard commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +        return getFilmByID(filmId);
Да, Александр, это решило проблему!!! Спасибо огромное!

2022-09-04 22:48 UTC, Anarmard commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +    public Optional<Film> createFilm(Film film) {
Убрал Optional в методе Create

2022-09-04 22:50 UTC, Anarmard commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/UserDbStorage.java
> +        return getUserByID(simpleJdbcInsert.executeAndReturnKey(toMapUser(user)).longValue());
Поправил

2022-09-04 23:01 UTC, Anarmard commented on src/main/resources/application.properties
> +spring.datasource.url=jdbc:h2:mem:filmorate
Если поставить сохранение в файл и запустить приложение "FilmorateApplication", то первый раз тесты постмана проходят как ожидаешь - что-то работает, что-то нет. Но вот если остановить приложение и снова его запустить и снова запустить тесты, то даже успешные тесты в 1-й попытке становятся неуспешными. 
Как я понял из slack, это из-за того, что в файле filmorate.mv.db при первом прохождении тестов сохраняются данные, которые и сбивают последующие запуски тестов. Там же в слаке прочитал, что можно поменять на память, чтобы каждый раз после прогона тестов не удалять вручную файл filmorate.mv.db

2022-09-04 23:12 UTC, Anarmard commented on src/test/java/ru/yandex/practicum/filmorate/FilmorateApplicationTests.java
> +		Optional<User> userOptional = userStorage.getUserByID(1L);
Александр, согласен с твоим комментарием!! Поправил - добавил создание фильма с id 1. Спасибо тебе!

Но вот наверное не до конца понимаю, что такое "ломается сборка". Даже с не работающим тестом FilmorateApplicationTest , приложение FilmorateApplication у меня почему-то запускался и запускается... И даже команда "mvn spring-boot:run" вроде срабатывает. "Неработающая сборка" - где можно увидеть, что сборка не работает?

2022-09-05 15:04 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/model/Mpa.java
> +    private Long ratingMpaId;
Я смотрел в постмане, но можно и в самом файле, это не принципиально где смотреть, там видно, что конкретно ожидается, и вот это вот "jsonData.id" и говорит об ожидаемом имени

2022-09-05 15:07 UTC, alexache commented on src/main/resources/application.properties
> +spring.datasource.url=jdbc:h2:mem:filmorate
Для локальной проверки можно не использовать файловое хранение, а вот для пуша в репозиторий лучше возвращать файловое хранение, в идеале это должны быть разные профили

2022-09-05 15:08 UTC, alexache commented on src/test/java/ru/yandex/practicum/filmorate/FilmorateApplicationTests.java
> +		Optional<User> userOptional = userStorage.getUserByID(1L);
Возможно проблема в моей вольной терминалогии, Я имею в виду сборку в гитхабе при пуше коммитов, сейчас она красная и написано в ПР, что есть "All checks have failed" с указанием на то, где что-то пошло не так

2022-09-05 15:24 UTC, alexache requested changes
Еще не проходит много тестов постмана

2022-09-05 15:24 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
>                      new Mpa(filmRow.getLong("RATING_MPA"), filmRow.getString("DESCRIPTION")),
Из-за этой строчки не проходит один из тестов постмана. Подсказка - у тебя description берется из таблицы фильма, а не рейтинга

2022-09-05 20:07 UTC, Anarmard commented on src/main/resources/application.properties
> +spring.datasource.url=jdbc:h2:mem:filmorate
Понял, когда буду делать пул реквест верну настройку обратно на сохранение в файле.

2022-09-05 20:08 UTC, Anarmard commented on src/test/java/ru/yandex/practicum/filmorate/FilmorateApplicationTests.java
> +		Optional<User> userOptional = userStorage.getUserByID(1L);
Ок, ясно!

2022-09-05 20:23 UTC, Anarmard commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
>                      new Mpa(filmRow.getLong("RATING_MPA"), filmRow.getString("DESCRIPTION")),
Аааа..... Александр, спасибо огромное! Я всё не мог понять, почему в процессе дебага на этой строке у меня происходила ошибка ... Теперь намного лучше! осталось пару тестов в постмане

2022-09-05 23:06 UTC, Anarmard commented
Постарался поправить ошибки на которые ты указал. Теперь все тесты в постмане проходят. Александр, спасибо за терпение!

2022-09-06 08:47 UTC, alexache approved these changes

2022-09-10 10:34 UTC, merged